name: "Bundlewatch GitHub Action"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Installing dependencies
        run: npm ci

      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
